name: Build SnapVideo

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean snapvideo.spec
    
    - name: Rename executable
      run: |
        copy dist\SnapVideo.exe SnapVideo.exe
      shell: cmd
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SnapVideo-Windows
        path: SnapVideo.exe
    
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: SnapVideo.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

